image: node:13.12.0

clone:
  depth: full

pipelines:
  branches:
    production:
      - step:
          name: App build
          caches:
            - node
          artifacts:
            - build/**
          script:
            - npm i
            - unset CI
            - npm run build
      - step:
          name: Deployment to prod
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/server/accountable-raso/www'
                LOCAL_PATH: 'build/*'
